#Run below command to trigger the ansible playbook
#ansible-playbook assignment-26-solution.yaml

- name: Import tasks with when condition
  hosts: localhost
  gather_facts: false
  vars:
    enable_configuration: true

- import_tasks: tasks/install_packages.yml

- import_tasks: tasks/configure_service.yml
  when: enable_configuration
