#Run below command to trigger the ansible playbook
#ansible-playbook assignment-24-solution.yaml

- name: Conditional tasks with loops
  hosts: localhost
  gather_facts: false
  vars:
    servers:
      - webserver-prod-01
      - appserver-dev-01
      - dbserver-prod-02

  tasks:
    - name: Print server type
      debug:
        msg: "Server {{ item }} is a production server."
      when: "'prod' in item"
      with_items: "{{ servers }}"
