#Run below command to trigger the ansible playbook
#ansible-playbook assignment-14-solution.yaml

---
- name: Manage files on remote servers
  hosts: all
  tasks:
    - name: Ensure file exists
      file:
        path: /var/app.log
        state: touch
