#Run below command to trigger the ansible playbook
#ansible-playbook assignment-11-solution.yaml

---
- name: Manage users on remote servers
  hosts: all
  tasks:
    - name: Create a user
      user:
        name: deploy
        state: present
        createhome: yes
        home: /home/deploy
