#Use Below command to ping all the Servers in the /root/inventory
#ansible -m ping all -i /root/inventory
#Playbook Solution Below
---
- name: Ping all servers
  hosts: all
  tasks:
    - name: Ping
      ping:

#Command to execute above playbook
#ansible-playbook assignment-1-solution.yaml -i /root/inventory
