#Run below command to trigger the ansible playbook
#ansible-playbook assignment-6-solution.yaml

---
- name: Update Web Servers
  hosts: webserver
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Create /var/www/html directory
      file:
        path: /var/www/html
        state: directory
